### ISSUE TITLE
Is the project still alive?

### ISSUE THREAD

**Issue by NathanHazout** [thlorenz/docmac#1]
I see that the last commit was in February 2014.
Is it because no changes were needed and everything still works fine?
Or was the project abandoned?

**Comment by bmedicke** [comment]
GitHub changed its user content domain and the cask install method is a bit different but other than that it should still work. I had a fix for that somewhere but have not bothered to create a pull request yet. 

There you go: https://github.com/thlorenz/docmac/pull/2

**Comment by thlorenz** [comment]
It's still alive, just haven't used it in a while.
@bmedicke just provided changes to bring it up to date.

> Is it because no changes were needed and everything still works fine?
> Or was the project abandoned?

Just because there is no commit activity doesn't mean it's dead even if I'm not actively adding changes (that can be done by people using it via a PR).
Usually I indicate in the Readme if something was abandoned.
